name = "chances-of-api"
main = "dist/cf/worker/src/index.js"
compatibility_date = "2024-01-01"

# Account: jamesredwards89@gmail.com
# Organization: Tailored Tools

[build]
command = "npm run build"

# Environment for production
[env.production]
name = "chances-of-api"
