name = "chances-of-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# Account: jamesredwards89@gmail.com
# Organization: Tailored Tools

[build]
command = "npm run build:worker"

# Environment for production
[env.production]
name = "chances-of-api"
